# Generated by Django 4.1.5 on 2023-01-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgar', '0004_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgar.raca'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
