# Generated by Django 4.1.5 on 2023-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoadocao',
            name='donosolicitacao',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
