# Generated by Django 4.1.5 on 2023-01-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0005_alter_pet_raca_alter_pet_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adotar', '0002_pedidoadocao_donosolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgar.pet'),
        ),
        migrations.AlterField(
            model_name='pedidoadocao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
